App/speedy7/core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name ='speedy'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assets/', views.assets, name='assets'),
    path('help/', views.help, name='help'),

    path('register/', views.registerPage, name='registerPage'),
    path('', views.loginPage, name='loginPage'),
    path('logout/', views.logoutUser, name='logoutUser'),
    
    path('users/', views.users, name='users'),
    path('user/', views.userView, name='userView'),
    path('user/edit/<int:id>', views.editUser, name='editUser'),
    path('user/delete/<int:id>', views.deleteUser, name='deleteUser'),
    path('user/password/change', views.changePass, name='changePass'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App/speedy7/speedy7/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path("", include('core.urls')),
    path("admin/", admin.site.urls),
]

App/speedy7/core/models.py
from django.db import models

    
class Log(models.Model):
    datetime = models.DateTimeField(blank=True, null=True)
    facility = models.CharField(max_length=20, blank=True, null=True)
    level = models.CharField(max_length=20, blank=True, null=True)
    host = models.CharField(max_length=32, blank=True, null=True)
    program = models.CharField(max_length=20, blank=True, null=True)
    pid = models.CharField(max_length=8, blank=True, null=True)
    message = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'log'

    

App/speedy7/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class EditUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email','is_active','first_name','last_name' ]
        

App/speedy7/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Log
from .filters import LogFilter
from dateutil import tz
import logging
import os
from datetime import datetime,timedelta
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout 
from .forms import *
from .templatetags.activityfilter import activityfilter

from django.contrib.auth.decorators import login_required

@login_required(login_url='/')
def dashboard(request):
    try:
        all_logs_query = Log.objects.order_by('-datetime').all
        all_logs = all_logs_query()

        # get all facilities
        facilities = set(item.facility for item in all_logs)

        # Get count of facilities
        fac_counter_dict = {}
        for facility in facilities:
            counter = 0
            for log in all_logs:
                if facility in log.facility:
                    counter += 1
            fac_counter_dict[facility] = counter

        # get last activities and number of events per host
        hosts = set(item.host for item in all_logs)
        last_activity_dict = {}
        host_counter_dict = {}
        for name in hosts:
            last_activity_dict[name] = Log.objects.order_by(
                '-datetime').filter(host=name).first()
            counter = 0
            for log in all_logs:
                if name in log.host:
                    counter += 1
            host_counter_dict[name] = counter

        # sort last_activity_dict by date
        sorted_last_activity_dict = dict(sorted(last_activity_dict.items(), key=lambda x : x[1].datetime, reverse=True))

        
        # tz = pytz.timezone("Europe/Warsaw")  -  set proper time zone

        # filter urgent logs
        incidents = tuple(log for log in Log.objects.order_by(
            'level') if (log.level in ['emerg','alert','crit','err'] ))
        logFilter = LogFilter(request.GET, queryset=all_logs)
        filteredLogs = logFilter.qs

        if 'time' in (req := request.GET) and req['time'] != '':
            minutes = req['time']
            filteredLogs = tuple(filter(lambda x: activityfilter(
                x.datetime, int(minutes)), filteredLogs))


        # prepare timechart values
        now = (n:=datetime.now()).replace(minute=(30 if n.minute > 30 else 0), second=0, microsecond=0)
        chart_hours = sorted(tuple(((now - timedelta(minutes=(x-1)*30)) for x in range(24))))
        activity_hours = dict(zip(chart_hours, [tuple()]*len(chart_hours)))
        for log in all_logs :
            if (time:=log.datetime.replace(minute=(30 if log.datetime.minute > 30 else 0), second=0, microsecond=0)) in chart_hours:
                activity_hours[time]+=(log,)


        context = {"all_logs": filteredLogs, "facilities": facilities,
                "hosts": hosts,
                "host_counter_dict": host_counter_dict,
                "fac_counter_dict": fac_counter_dict,
                "incidents": incidents,
                "activity_hours": activity_hours,
                "last_activity_dict": sorted_last_activity_dict,
                "myFilter": logFilter}

        
        return render(request, 'speedy/dashboard.html', context)
    except Exception:
        logging.info('No messages')
        return render(request, 'speedy/dashboard.html', {})
        

@login_required(login_url='/')
def users(request):
    users = User.objects.all()
    context = {'users':users}
    return render(request, 'accounts/users.html',context)
    
@login_required(login_url='/')
def assets(request):
    
    try:
        all_logs = Log.objects.all()
        hosts = set(item.host for item in all_logs)
        
        host_info_dict = {}
        # host_counter_dict = {}
        for name in hosts:
            last_activity = var if (var:=Log.objects.order_by('-datetime').filter(host=name).first().datetime) else None
            counter = 0
            for log in all_logs:
                if name in log.host:
                    counter += 1
            host_info_dict[name]=(last_activity,counter)

        if request.method == "POST":
            hostname = request.POST.get('host')
            is_online = 2 if os.system("ping -c 1 " + hostname) == 0 else 1
            context = {'host':hostname,'hosts':host_info_dict, 'is_online':is_online}
            return render(request, 'speedy/assets.html',context)
        
        context = {'hosts':host_info_dict}
        return render(request, 'speedy/assets.html',context)
    except Exception:
        logging.info('No messages')
        return render(request, 'speedy/assets.html', {})

@login_required(login_url='/')
def help(request):
   
    context = {}
    return render(request, 'speedy/help.html',context) 


def registerPage(request):
    
    if request.user.is_authenticated:
        return redirect('dashboard/')

    form = RegisterForm()
    
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Account was created for " + user)

            return redirect('/')

    context = {'form':form}
    return render(request, 'accounts/register.html', context=context)

def loginPage(request):

    if request.user.is_authenticated:
        return redirect('dashboard/')
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('dashboard/')
        else:
            messages.info(request, 'Username OR password is incorrect')
        
    context = {}
    return render(request, 'accounts/login.html', context=context)

@login_required(login_url='/')
def userView(request):
    user = User.objects.get(pk=request.user.id)
    context = {'user':user}
    return render(request, 'accounts/me.html', context=context)

@login_required(login_url='/')
def editUser(request,id):
    return redirect('/admin/auth/user/%s/change/' % (id,))
    
@login_required(login_url='/')
def deleteUser(request,id):
    return redirect('/admin/auth/user/%s/delete/' % (id,))

@login_required(login_url='/')
def changePass(request):
    id = request.user.id
    return redirect('/admin/auth/user/%s/password/' % (id,))

@login_required(login_url='/')
def logoutUser(request):
    logout(request)
    return redirect('/')


    # user = User.objects.get(pk=id)
    # userToEdit = EditUserForm(instance = user)

    # if request.method == 'POST':
    #     user = User.objects.get(username=request.POST.get('username'))
    #     edit_user_form = EditUserForm(request.POST, instance = user)
    #     if edit_user_form.is_valid:
    #         # user_to_edit = User.objects.get(username=request.POST['username'])
    #         edit_user_form.save(commit=False)
    #         messages.success(request, "Account was edited for ")
    #         return redirect('/users')
    
    # context = {'form':userToEdit}
    
    # return render(request, 'accounts/edit.html', context=context)

App/speedy7/core/templates/accounts/edit.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Login{%endblock%}
{% block content %}
    <div class="container login">
        <br>
        <br>
        <h1>Speedy7</h1>
        <br>
        <br>
        <br>
        <h5>Edit user</h5>
        <hr style="border: 1px solid #2d2d49;"></hr>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="login" value="Log in">
        </form>

        {% for message in messages %}
            <p id="messages">{{message}}</p>
        {% endfor %}

    </div>

{% endblock %}

App/speedy7/core/templates/accounts/login.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Login{%endblock%}
{% block content %}
    <div class="container login">
        <br>
        <br>
        <h1>Speedy7</h1>
        <br>
        <br>
        <br>
        <h5>Login</h5>
        <hr style="border: 1px solid #2d2d49;"></hr>
        <form method="POST">
            {% csrf_token %}
            Username
            <input type="text" name="username" placeholder="Username" class=""></input>
            Password
            <input type="password" name="password" placeholder="Password" class=""></input>
            <input type="submit" name="login" value="Log in">
        </form>

        {% for message in messages %}
            <p style="color: red" id="messages">{{message}}</p>
        {% endfor %}

        <p>Don't have an account? <a href="{% url 'speedy:registerPage' %}">Register</a>.</p>
    </div>
{% endblock %}

App/speedy7/core/templates/accounts/me.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}User{%endblock%}
{% block content %}
{% include 'speedy/menu.html' %}

    <div class="container">
        <h1 style="text-align: center">Hello, {{user.username}}!</h1>
        <br>
        <br>
       
                    <table class="">

                        <tbody id="myTable">
                            
                            <tr class="">
                                <td class="header2">Id</td>
                                <td>{{user.id}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Username</td>
                                <td>{{user.username}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Email</td>
                                <td>{{user.email}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">First name</td>
                                <td>{{user.first_name}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Last name</td>
                                <td>{{user.last_name}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Date joined</td>
                                <td>{{user.date_joined}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Is staff</td>
                                <td>{{user.user.is_staff|yesno}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Is active</td>
                                <td>{{user.is_active|yesno}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Is superuser</td>
                                <td>{{user.is_superuser|yesno}}</td>
                            </tr>
                            <tr class="">
                                <td class="header2">Last login</td>
                                <td>{% if user.last_login %}{{user.last_login}}{% else %}Never{% endif %}</td>
                            </tr>

                            
                        </tbody>
                    </table>

    </div>
{% endblock %}

App/speedy7/core/templates/accounts/register.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Register{%endblock%}
{% block content %}
    <div class="container login">
        <br>
        <br>
        <h1>Speedy7</h1>
        <br>
        <br>
        <br>
        <h5>Register</h5>
        <hr style="border: 1px solid #2d2d49;"></hr>
        <form method="POST" action="">  
            {% csrf_token %} 
            Username
            <input type="text" name="username" placeholder="Username" class=""></input>
            Email address
            <input type="text" name="email" placeholder="email" class=""></input>
            Password
            <input type="password" name="password1" placeholder="Password" class=""></input>
            Confirm password
            <input type="password" name="password2" placeholder="Password" class=""></input>
            {{form.errors}}
            <input type="submit" name="register" value="Create User">
        </form>
        
        <p>Already have an account? <a href="{% url 'speedy:loginPage' %}">Login</a>.</p>
    </div>


{% endblock %}

App/speedy7/core/templates/accounts/users.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Users{%endblock%}
{% block content %}
{% include 'speedy/menu.html' %}

    <div class="container">
        <h1 style="text-align: center">Users</h1>
        <br>
        <br>
        <table class="sortable">
            <thead>
                <tr class="header2">
                    <td>Id</td>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Last Login</td>
                    <td>Staff</td>
                    <td>Superuser</td>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Active</td>
                    <td>Date Joined</td>
                    <td></td>
                    <td></td>
                    {% comment %} <td></td> {% endcomment %}
                </tr>
            </thead>

            <tbody id="myTable">
                {% for user in users %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.username}}</td>
                        <td>{{user.email}}</td>
                        <td>{% if user.last_login %}{{user.last_login}}{% else %}Never{% endif %}</td>
                        <td>{% if user.is_staff %}<span>&#x2713;</span>{% else %}<span>&#x2717;</span>{% endif %}</td>
                        <td>{% if user.is_superuser %}<span>&#x2713;</span>{% else %}<span>&#x2717;</span>{% endif %}</td>
                        <td>{{user.first_name}}</td>
                        <td>{{user.last_name}}</td>
                        <td>{% if user.is_active %}<span>&#128994;</span>{% else %}<span>&#128308;</span>{% endif %}</td>
                        <td>{{user.date_joined}}</td>
                        <td><a href="{% url 'speedy:editUser' id=user.id %}">Edit</a></td>
                        <td><a href="{% url 'speedy:deleteUser' id=user.id %}">Delete</a></td>
                        {% comment %} <td><a href="">Deactive</a></td> {% endcomment %}
                    </tr>

                {% endfor %}
            </tbody>
        </table>
    
    </div>
{% endblock %}