App/speedy7/core/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name ='speedy'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assets/', views.assets, name='assets'),
    path('help/', views.help, name='help'),

    path('register/', views.registerPage, name='registerPage'),
    path('', views.loginPage, name='loginPage'),
    path('logout/', views.logoutUser, name='logoutUser'),
    
    path('users/', views.users, name='users'),
    path('user/', views.userView, name='userView'),
    path('user/edit/<int:id>', views.editUser, name='editUser'),
    path('user/delete/<int:id>', views.deleteUser, name='deleteUser'),
    path('user/password/change', views.changePass, name='changePass'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App/speedy7/speedy7/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path("", include('core.urls')),
    path("admin/", admin.site.urls),
]

App/speedy7/core/models.py
from django.db import models

    
class Log(models.Model):
    datetime = models.DateTimeField(blank=True, null=True)
    facility = models.CharField(max_length=20, blank=True, null=True)
    level = models.CharField(max_length=20, blank=True, null=True)
    host = models.CharField(max_length=32, blank=True, null=True)
    program = models.CharField(max_length=20, blank=True, null=True)
    pid = models.CharField(max_length=8, blank=True, null=True)
    message = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'log'

    

App/speedy7/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class EditUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email','is_active','first_name','last_name' ]
        

App/speedy7/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Log
from .filters import LogFilter
from dateutil import tz
import logging
import os
from datetime import datetime,timedelta
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout 
from .forms import *
from .templatetags.activityfilter import activityfilter

from django.contrib.auth.decorators import login_required

@login_required(login_url='/')
def dashboard(request):
    try:
        all_logs_query = Log.objects.order_by('-datetime').all
        all_logs = all_logs_query()

        # get all facilities
        facilities = set(item.facility for item in all_logs)

        # Get count of facilities
        fac_counter_dict = {}
        for facility in facilities:
            counter = 0
            for log in all_logs:
                if facility in log.facility:
                    counter += 1
            fac_counter_dict[facility] = counter

        # get last activities and number of events per host
        hosts = set(item.host for item in all_logs)
        last_activity_dict = {}
        host_counter_dict = {}
        for name in hosts:
            last_activity_dict[name] = Log.objects.order_by(
                '-datetime').filter(host=name).first()
            counter = 0
            for log in all_logs:
                if name in log.host:
                    counter += 1
            host_counter_dict[name] = counter

        # sort last_activity_dict by date
        sorted_last_activity_dict = dict(sorted(last_activity_dict.items(), key=lambda x : x[1].datetime, reverse=True))

        
        # tz = pytz.timezone("Europe/Warsaw")  -  set proper time zone

        # filter urgent logs
        incidents = tuple(log for log in Log.objects.order_by(
            'level') if (log.level in ['emerg','alert','crit','err'] ))
        logFilter = LogFilter(request.GET, queryset=all_logs)
        filteredLogs = logFilter.qs

        if 'time' in (req := request.GET) and req['time'] != '':
            minutes = req['time']
            filteredLogs = tuple(filter(lambda x: activityfilter(
                x.datetime, int(minutes)), filteredLogs))


        # prepare timechart values
        now = (n:=datetime.now()).replace(minute=(30 if n.minute > 30 else 0), second=0, microsecond=0)
        chart_hours = sorted(tuple(((now - timedelta(minutes=(x-1)*30)) for x in range(24))))
        activity_hours = dict(zip(chart_hours, [tuple()]*len(chart_hours)))
        for log in all_logs :
            if (time:=log.datetime.replace(minute=(30 if log.datetime.minute > 30 else 0), second=0, microsecond=0)) in chart_hours:
                activity_hours[time]+=(log,)


        context = {"all_logs": filteredLogs, "facilities": facilities,
                "hosts": hosts,
                "host_counter_dict": host_counter_dict,
                "fac_counter_dict": fac_counter_dict,
                "incidents": incidents,
                "activity_hours": activity_hours,
                "last_activity_dict": sorted_last_activity_dict,
                "myFilter": logFilter}

        
        return render(request, 'speedy/dashboard.html', context)
    except Exception:
        logging.info('No messages')
        return render(request, 'speedy/dashboard.html', {})
        

@login_required(login_url='/')
def users(request):
    users = User.objects.all()
    context = {'users':users}
    return render(request, 'accounts/users.html',context)
    
@login_required(login_url='/')
def assets(request):
    
    try:
        all_logs = Log.objects.all()
        hosts = set(item.host for item in all_logs)
        
        host_info_dict = {}
        # host_counter_dict = {}
        for name in hosts:
            last_activity = var if (var:=Log.objects.order_by('-datetime').filter(host=name).first().datetime) else None
            counter = 0
            for log in all_logs:
                if name in log.host:
                    counter += 1
            host_info_dict[name]=(last_activity,counter)

        if request.method == "POST":
            hostname = request.POST.get('host')
            is_online = 2 if os.system("ping -c 1 " + hostname) == 0 else 1
            context = {'host':hostname,'hosts':host_info_dict, 'is_online':is_online}
            return render(request, 'speedy/assets.html',context)
        
        context = {'hosts':host_info_dict}
        return render(request, 'speedy/assets.html',context)
    except Exception:
        logging.info('No messages')
        return render(request, 'speedy/assets.html', {})

@login_required(login_url='/')
def help(request):
   
    context = {}
    return render(request, 'speedy/help.html',context) 


def registerPage(request):
    
    if request.user.is_authenticated:
        return redirect('dashboard/')

    form = RegisterForm()
    
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Account was created for " + user)

            return redirect('/')

    context = {'form':form}
    return render(request, 'accounts/register.html', context=context)

def loginPage(request):

    if request.user.is_authenticated:
        return redirect('dashboard/')
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('dashboard/')
        else:
            messages.info(request, 'Username OR password is incorrect')
        
    context = {}
    return render(request, 'accounts/login.html', context=context)

@login_required(login_url='/')
def userView(request):
    user = User.objects.get(pk=request.user.id)
    context = {'user':user}
    return render(request, 'accounts/me.html', context=context)

@login_required(login_url='/')
def editUser(request,id):
    return redirect('/admin/auth/user/%s/change/' % (id,))
    
@login_required(login_url='/')
def deleteUser(request,id):
    return redirect('/admin/auth/user/%s/delete/' % (id,))

@login_required(login_url='/')
def changePass(request):
    id = request.user.id
    return redirect('/admin/auth/user/%s/password/' % (id,))

@login_required(login_url='/')
def logoutUser(request):
    logout(request)
    return redirect('/')


    # user = User.objects.get(pk=id)
    # userToEdit = EditUserForm(instance = user)

    # if request.method == 'POST':
    #     user = User.objects.get(username=request.POST.get('username'))
    #     edit_user_form = EditUserForm(request.POST, instance = user)
    #     if edit_user_form.is_valid:
    #         # user_to_edit = User.objects.get(username=request.POST['username'])
    #         edit_user_form.save(commit=False)
    #         messages.success(request, "Account was edited for ")
    #         return redirect('/users')
    
    # context = {'form':userToEdit}
    
    # return render(request, 'accounts/edit.html', context=context)

App/speedy7/core/templates/speedy/assets.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Assets{%endblock%}
{% block content %}
{% include 'speedy/menu.html' %}

    <div class="container">
        <h1 style="text-align: center">Hosts</h1>
        <br>
        <br>
        <table class="sortable">
            <thead>
                <tr class="header2">
                    <td>Name</td>
                    <td>Last Activity</td>
                    <td>Events</td>
                    <td>Check availibility</td>
                    
                </tr>
            </thead>

            <tbody id="myTable">
                {% for name,info in hosts.items %}
                    <tr>
                        <td>{{name}}</td>
                        <td>{{info.0}}</td>
                        <td>{{info.1}}</td>
                        <form id="connectivity_check" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="host" value="{{name}}" /> 
                            {% if is_online and name == host%}
                                <td><a>{% if is_online == 2%}<span>&#128994;</span>Online{% elif is_online == 1 %} <span>&#128308;</span>Offline{% else %}Unknown{% endif %}</a></td>
                            {% else %}
                            <td><input type="submit" style="padding: 0; border: none; background: none; color: blue;" value="Check"></td>
                            {% endif %}
                        </form>
                    </tr>
                
                {% endfor %}
            </tbody>
        </table>
    
    </div>

    <script>

        function submitFunction() {
            document.getElementById("connectivity_check").submit();
        }
    </script>

    
{% endblock %}

App/speedy7/core/templates/speedy/base.html
{% load static %}{% spaceless %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}base{% endblock %}</title>
    {% block head %}{% endblock %}
  </head>
  <body id="body">
    {% block content %}
      
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      

    <script async src="{% static 'sorttable.js' %}"></script>
  </body>
</html>
{% endspaceless %}

App/speedy7/core/templates/speedy/dashboard.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load activityfilter %}
{% load counter %}

{%block title%}Dashboard{%endblock%}
{% block content %}
{% include 'speedy/menu.html' %}
    
    <script>
          setTimeout(() => {
            document.location.reload();
          }, 60000);

          function search(){
            var input, filter, table, tr, td, i;
            input = document.getElementById("globalInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
          
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td") ; 
              for(j=0 ; j<td.length ; j++)
              {
                let tdata = td[j] ;
                if (tdata) {
                  if (tdata.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                    break ; 
                  } else {
                    tr[i].style.display = "none";
                  }
                } 
              }
            }
          }
    </script> 

    
    <div class="container">
      <div class="search_container">
        <div class="prop_search">
          <form method="get">
            Host:<select name="host">
              <option value="">All</option>
              {% for host in hosts %}
                <option value="{{host}}">{{host}}</option>
              {% endfor %}
            </select>
            Facility:<select name="facility">
              <option value="">All</option>
              {% for facility in facilities %}
                <option value="{{facility}}">{{facility}}</option>
              {% endfor %}
            </select>   
            Time:<select name="time">
              <option value="">All</option>
              <option value="15">Last 15 minutes</option>
              <option value="30">Last 30 minutes</option>
              <option value="240">Last 4 hours</option>
            </select>   
            <button class="search_button" type="submit"><i class="fa fa-search"></i></button>
          </form>
        </div>
        <div class="global_search">
          <input type="text" id="globalInput" class="input-text-log" onkeyup="search()" placeholder="Search">
        </div>
      </div>
      <div class="log_table">
            <table class="sortable">
                <thead>
                    <tr class="header2">
                        <td>PID</td>
                        <td>Message</td>
                        <td>Program</td>
                        <td>Facility</td>
                        <td>Host</td>
                        <td>Level</td>
                        <td>Timestamp</td>
                    </tr>
                </thead>

                <tbody id="myTable">
                    {% for log in all_logs %}
                        <tr>
                            <td>{{log.pid}}</td>
                            <td>{{log.message}}</td>
                            <td>{{log.program}}</td>
                            <td>{{log.facility}}</td>
                            <td>{{log.host}}</td>
                            <td>{{log.level}}</td>
                            <td>{{log.datetime}}</td>
                        </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
          </div>
    </div>

    <div class="graphs">
      <div class="card1"> <h4>Events based on host</h4> <canvas id="barChart"></canvas></div>
      
      <div class="card2"><h3>Activity line chart</h3><canvas id="lineChart"></canvas></div>
    </div>

    <div class="graphs2">
      <div class="card3">
        
        <h3>Incidents</h3> 
          <div class="inc_table">
           <table class="sortable">
            <thead>
                <tr class="header2">
                    <td>Urgency</td>
                    <td>Level</td>
                    <td>Host</td>
                    <td>Facility</td>
                    <td>Message</td>
                    <td>Timestamp</td>
                </tr>
            </thead>

            <tbody id="myTable">
                {% for inc in incidents %}
                    <tr>
                    {% comment %} <tr style="background-color: {% if inc.level == 'local0' %}#a1070275{% elif inc.level == 'local1' %}#610f7f49{% elif inc.level == 'local2' %}#ec9b2973{% elif inc.level == 'local3' %}#ec9b2973{% endif %}"> {% endcomment %}
                      {% comment %} add href to full, and create asset view {% endcomment %}
                        <td style="text-align: center; color: red;">{% if inc.level == 'emerg' %}<span>&#9888;&#9888;&#9888;&#9888;</span>{% elif inc.level == 'alert' %}&#9888;&#9888;&#9888;{% elif inc.level == 'crit' %}&#9888;&#9888;{% elif inc.level == 'err' %}&#9888;{% endif %}</td>
                        <td>{{inc.level}}</td>
                        <td>{{inc.host}}</td>
                        <td>{{inc.facility}}</td>
                        <td>{{inc.message}}</td>
                        <td>{{inc.datetime}}</td>
                      
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>


      <div class="card4"><h3>Events based on facility</h3><canvas id="doughnutChart"></canvas></div>
      <div class="card5"> 
        <h3>Last active hosts</h3>
        <table class="sortable" style="">
          <thead>
              <tr class="header2">
                  <td>Name</td>
                  <td>Last activity</td>
              </tr>
          </thead>
          <tbody id="myTable">
              {% for host, log in last_activity_dict.items %}
                  <tr>
                      <td>{% if log.datetime|activityfilter:10 %}
                            <span>&#128994;</span>
                          {% elif log.datetime|activityfilter:120 %}
                            <span>&#128993;</span>
                          {% else %}
                            <span>&#128308;</span>
                          {% endif %}{{host}}
                      </td>
                      <td>{{log.datetime|timesince}} ago</td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
      </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/moment@^2"></script>
    <script src="{% static 'chart.js' %}"></script>
    <script>
      const barChart = document.getElementById('barChart');
    
      new Chart(barChart, {
        type: 'bar',
        data: {
          labels: [{% for host,value in host_counter_dict.items %} "{{host}}", {% endfor %}],
          datasets: [{
            label: ['Events'],
            backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
            data: [{% for host,value in host_counter_dict.items %} "{{value}}", {% endfor %}],
            borderWidth: 1
          }]
        },
        options: {
          plugins: {
            legend: {
                display: false,
                labels: {
                    color: ''
                }
            }
          },
          scales: {
            y: {
              beginAtZero: true
            }
          }, animation: {
            duration: 3000,
        }, responsive: true,
        }

      });
    </script>

    <script>
      const doughnutChart = document.getElementById('doughnutChart');
    
      new Chart(doughnutChart, {
        type: 'doughnut',
        data: {
          labels: [{% for host,value in fac_counter_dict.items %} "{{host}}", {% endfor %}],
          datasets: [{
            label: '',
            backgroundColor: ["#e8c3b9","#c45850","#3e95cd", "#8e5ea2","#3cba9f", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
            data: [{% for host,value in fac_counter_dict.items %} "{{value}}", {% endfor %}],
            hoverOffset: 4,
            borderWidth: 0
          }]
        },
        options: {
          animation: {
            duration: 3000,
        }, responsive: true,
        }
      });
    </script>


    <script src="{% static 'utils.js' %}"></script>
    <script>
      const Utils = ChartUtils.init();
      const lineChart = document.getElementById('lineChart');
      // create filter that will receive x hours back from last event
      const labels = [{% for datetime, log in activity_hours.items %} "{{datetime|date:'M d - H:i'}}", {% endfor %}];

      new Chart(lineChart, {
        type: 'line',
        data: {
          labels: labels,
          datasets: [{ 
            
            label: "Activity",
            data: [{% for datetime, log_table in activity_hours.items %}
                    {% if log_table %} 
                      {{ log_table|counter }},
                    {% else %}
                    ,
                    {% endif %}
                  {% endfor %}],
            fill: true,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1

          }]
        }, 
        options: {
          plugins: {
            legend: {
                display: false,
                labels: {
                    color: ''
                }
            }
          },
          scales: {
            x: {
              beginAtZero: true
            }
          },
          animation: {
            duration: 3000, 
        }, responsive: true, showLine: true, aspectRatio:2|3 ,spanGaps: false, fill: true, pointBackgroundColor: 'rgb(75, 192, 192)',
        }
      });

    </script>
    

{% include 'speedy/footer.html' %}
{% endblock %}

App/speedy7/core/templates/speedy/footer.html
<div class="footer">
    <div class="footer1">
    </div>
    <div class="footer2">
            <p style="float:left">speedy7</p>
            <p style="float:right">@bmarek</p>
    </div>
</div>

App/speedy7/core/templates/speedy/help.html
{% extends 'speedy/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Help{%endblock%}
{% block content %}
{% include 'speedy/menu.html' %}

    <div class="container">
        <h1>HELP</h1>
    <p>This is an app to display logs fetched using syslog-ng.</p>

    <table class="wikitable">
        <h2>FACILITIES</h2>
        <hr style="border: 1px solid #2d2d49;"></hr>
        <tbody><tr>
        <th>Facility code
        </th>
        <th>Keyword
        </th>
        <th>Description
        </th></tr>
        <tr>
        <td>0</td>
        <td>kern</td>
        <td>Kernel messages
        </td></tr>
        <tr>
        <td>1</td>
        <td>user</td>
        <td>User-level messages
        </td></tr>
        <tr>
        <td>2</td>
        <td>mail</td>
        <td>Mail system
        </td></tr>
        <tr>
        <td>3</td>
        <td>daemon</td>
        <td>System daemons
        </td></tr>
        <tr>
        <td>4</td>
        <td>auth</td>
        <td>Security/authentication messages
        </td></tr>
        <tr>
        <td>5</td>
        <td>syslog</td>
        <td>Messages generated internally by syslogd
        </td></tr>
        <tr>
        <td>6</td>
        <td>lpr</td>
        <td>Line printer subsystem
        </td></tr>
        <tr>
        <td>7</td>
        <td>news</td>
        <td>Network news subsystem
        </td></tr>
        <tr>
        <td>8</td>
        <td>uucp</td>
        <td>UUCP subsystem
        </td></tr>
        <tr>
        <td>9</td>
        <td>cron</td>
        <td>Cron subsystem
        </td></tr>
        <tr>
        <td>10</td>
        <td>authpriv</td>
        <td>Security/authentication messages
        </td></tr>
        <tr>
        <td>11</td>
        <td>ftp</td>
        <td>FTP daemon
        </td></tr>
        <tr>
        <td>12</td>
        <td>ntp</td>
        <td>NTP subsystem
        </td></tr>
        <tr>
        <td>13</td>
        <td>security</td>
        <td>Log audit
        </td></tr>
        <tr>
        <td>14</td>
        <td>console</td>
        <td>Log alert
        </td></tr>
        <tr>
        <td>15</td>
        <td>solaris-cron</td>
        <td>Scheduling daemon
        </td></tr>
        <tr>
        <td>16–23</td>
        <td>local0 – local7</td>
        <td>Locally used facilities
        </td></tr></tbody></table>
        <hr style="border: 4px solid #2d2d49;"></hr>
        <h2>LEVELS</h2>        
        <hr style="border: 1px solid #2d2d49;"></hr>
        <table>

            <tbody><tr>
            <th>Value</th>
            <th>Severity</th>
            <th>Keyword</th>
            <th>Deprecated keywords</th>
            <th>Description</th>
            <th>Condition
            </th></tr>
            <tr>
            <td>0</td>
            <td>Emergency</td>
            <td><code>emerg</code></td>
            <td><code>panic</code></td>
            <td>System is unusable</td>
            <td>A panic condition.
            </td></tr>
            <tr>
            <td>1</td>
            <td>Alert</td>
            <td><code>alert</code></td>
            <td></td>
            <td>Action must be taken immediately</td>
            <td>A condition that should be corrected immediately, such as a corrupted system database.
            </td></tr>
            <tr>
            <td>2</td>
            <td>Critical</td>
            <td><code>crit</code></td>
            <td></td>
            <td>Critical conditions</td>
            <td>Hard device errors.
            </td></tr>
            <tr>
            <td>3</td>
            <td>Error</td>
            <td><code>err</code></td>
            <td><code>error</code></td>
            <td>Error conditions</td>
            <td>
            </td></tr>
            <tr>
            <td>4</td>
            <td>Warning</td>
            <td><code>warning</code></td>
            <td><code>warn</code></td>
            <td>Warning conditions</td>
            <td>
            </td></tr>
            <tr>
            <td>5</td>
            <td>Notice</td>
            <td><code>notice</code></td>
            <td></td>
            <td>Normal but significant conditions</td>
            <td>Conditions that are not error conditions, but that may require special handling.
            </td></tr>
            <tr>
            <td>6</td>
            <td>Informational</td>
            <td><code>info</code></td>
            <td></td>
            <td>Informational messages</td>
            <td>Confirmation that the program is working as expected.
            </td></tr>
            <tr>
            <td>7</td>
            <td>Debug</td>
            <td><code>debug</code></td>
            <td></td>
            <td>Debug-level messages</td>
            <td>Messages that contain information normally of use only when debugging a program.
            </td></tr></tbody></table>
            <hr style="border: 4px solid #2d2d49;"></hr>
            <h2>SYSLOG MESSAGE SYNTAX</h2>        
            <hr style="border: 1px solid #2d2d49;"></hr>
            <p>${R_FULLDATE}","${FACILITY}","${LEVEL}", "${HOST}", "${PROGRAM}", "${PID}", "${MSGONLY}"</p>

    </div>

{% endblock %}

App/speedy7/core/templates/speedy/menu.html
<div id="menu">
    <div class="submenu">
        <ul>
            <li><a href="{% url 'speedy:dashboard' %}">Home</a></li>
            {% if request.user.is_superuser %}
                <li><a href="{% url 'speedy:users' %}">Users</a></li>
            {% endif %}
            <li><a href="{% url 'speedy:assets' %}">Assets</a></li>
            {% comment %} <li><a href="">Connector</a></li> {% endcomment %}
            <li><a href="{% url 'speedy:help' %}">Help</a></li>
            <li style="float:right"><a href="{% url 'speedy:logoutUser' %}">Logout</a></li>
            {% if request.user.is_superuser %}
                <li style="float:right"><a href="{% url 'speedy:changePass' %}">Change password</a></li>
            {% endif %}
            <li style="float:right"><a href="{% url 'speedy:userView' %}">You are logged as {{request.user}}</a></li>
        </ul>     
    </div>
</div>